### ISSUE TITLE
[SMB Blueprint] Make use of managed disks for all vm's

### ISSUE THREAD

**Issue by Stijnc** [Inovativ/Feedback#5]
Adopt the new managed disks feature and remove all storage accounts (except for logging).

managed disks provides an abstraction layer between the VM and the storage accounts, so no more storage account management needed. (one of the benefits)
Also it eases the migration from standard to premium disks etc.

More info about managed disks can be found here: [microsoft docs](https://docs.microsoft.com/en-us/azure/storage/storage-managed-disks-overview)

**Comment by JanVanMeirvenne** [comment]
Added in version 8.1
